theme = "taxi"

[editor]
popup-border = "all"
line-number = "relative"
mouse = true
bufferline = "always"
true-color = true
color-modes = true
end-of-line-diagnostics = "hint"
auto-format = true

[editor.indent-guides]
render = true

[editor.lsp]
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
G = "goto_file_end"
X = "extend_line_above"
C-s = ["save_selection", ":w"]
H = ":toggle lsp.display-inlay-hints"
I = ":toggle indent-guides.render"
  
[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-type", "file-encoding", "file-line-ending"]
